#! /bin/bash

echo Generating dataset
test-rtree-Generator 100 0 > d
awk '{if ($1 != 2) print $0}' < d > data
awk '{if ($1 == 2) print $0}' < d > queries
rm -rf d

echo Creating new R-Tree
test-rtree-RTreeLoad data tree 5 10NN

echo Querying R-Tree
test-rtree-RTreeQuery queries tree 10NN > res